# Generated by Django 5.2 on 2025-04-11 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='model',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='departure',
            new_name='origin',
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cargo',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.flight'),
        ),
    ]
