# Generated by Django 5.2 on 2025-04-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_rename_model_aircraft_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='cargo_id',
            field=models.CharField(default=1, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
