# Generated by Django 5.2 on 2025-04-11 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_cargo_cargo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='flight',
        ),
        migrations.AddField(
            model_name='cargo',
            name='Aircraft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.aircraft'),
            preserve_default=False,
        ),
    ]
