# Generated by Django 5.2 on 2025-04-15 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_remove_cargo_flight_cargo_aircraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance_km', models.FloatField()),
                ('average_speed_kmph', models.FloatField(default=800)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='distance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.distance'),
            preserve_default=False,
        ),
    ]
